name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Drop test DB if exists
      run: |
        psql ${{ secrets.DATABASE_URL }} -c "DROP DATABASE IF EXISTS test_491project;" || true

    - name: Run Django Tests
      working-directory: ./backend
      run: python manage.py test --noinput
